url                      : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl                  : "/" # the subpath of your site, e.g. /blog
title                    : "The Software Consultant Library" # the name of your site, e.g. ACME Corp.
repository               : "mivano/software-consultant-books"

comments:
  provider               : "giscus" # false (default), "giscus", "custom"
  giscus:
    repo_id              : "R_kgDOIk8VGQ"
    category_name        : "Announcements"
    category_id          : "DIC_kwDOIk8VGc4CS9rY"
    discussion_term      : "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
    theme                : "preferred_color_scheme" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

# Analytics
analytics:
  provider               : false #"google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "" # Replace this with your ID, or delete

collections:
  books:
    output: true
    permalink: /:collection/:name    

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"

sass:
    load_paths: 
        - _sass
    style: compressed

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - readme.md
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache